### ISSUE TITLE
Installation instructions missing for OS X?

### ISSUE THREAD

**Issue by akshayl** [vmware/vca-cli#10]
When I try to log in to an instance like so:

    vca login akshay.luther@gmail.com --instance "abe380c7-ebd0-4417-927a-a9b88e596ae3"

I get an error:

    Traceback (most recent call last):
      File "//anaconda/bin/vca", line 9, in <module>
        load_entry_point('vca-cli==10', 'console_scripts', 'vca')()
      File "//anaconda/lib/python2.7/site-packages/click/core.py", line 664, in __call__
        return self.main(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/click/core.py", line 644, in main
        rv = self.invoke(ctx)
      File "//anaconda/lib/python2.7/site-packages/click/core.py", line 991, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "//anaconda/lib/python2.7/site-packages/click/core.py", line 837, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "//anaconda/lib/python2.7/site-packages/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 239, in login
        result = _login_user_to_service(ctx, user, host, password, service_type, service_version, instance, org)
      File "//anaconda/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 170, in _login_user_to_service
        result = vca.login_to_instance(instance, password, None, None)
      File "//anaconda/lib/python2.7/site-packages/pyvcloud/vcloudair.py", line 177, in login_to_instance
        result = vcloud_session.login(password, token)
      File "//anaconda/lib/python2.7/site-packages/pyvcloud/vcloudsession.py", line 65, in login
        session = sessionType.parseString(self.response.content, True)
      File "//anaconda/lib/python2.7/site-packages/pyvcloud/schema/vcd/v1_5/schemas/vcloud/sessionType.py", line 5225, in parseString
        rootObj.build(rootNode)
      File "//anaconda/lib/python2.7/site-packages/pyvcloud/schema/vcd/v1_5/schemas/vcloud/sessionType.py", line 5101, in build
        self.buildAttributes(node, node.attrib, already_processed)
      File "//anaconda/lib/python2.7/site-packages/pyvcloud/schema/vcd/v1_5/schemas/vcloud/sessionType.py", line 5119, in buildAttributes
        super(SessionType, self).buildAttributes(node, attrs, already_processed)
      File "//anaconda/lib/python2.7/site-packages/pyvcloud/schema/vcd/v1_5/schemas/vcloud/sessionType.py", line 1215, in buildAttributes
        value = find_attr_value_('xsi:type', node)
      File "//anaconda/lib/python2.7/site-packages/pyvcloud/schema/vcd/v1_5/schemas/vcloud/sessionType.py", line 492, in find_attr_value_
        namespace = node.nsmap.get(prefix)
    AttributeError: nsmap

**Comment by pacogomez** [comment]
Please try this:

brew install libxml2
brew install libxslt
brew link libxml2 --force
brew link libxslt --force

**Comment by akshayl** [comment]
aluther ~ $ brew link libxml2 --force
    Linking /usr/local/Cellar/libxml2/2.9.2...
    Error: Could not symlink include/libxml2
    /usr/local/include is not writable.
    aluther ~ $ brew link libxslt --force
    Linking /usr/local/Cellar/libxslt/1.1.28_1...
    Error: Could not symlink include/libexslt
    /usr/local/include is not writable.

**Comment by pacogomez** [comment]
try this:
sudo chown -R $USER /usr/local/include
brew install libxml2
brew install libxslt
brew link libxml2 --force
brew link libxslt --force

**Comment by pacogomez** [comment]
Did this solve this issue?

**Comment by pacogomez** [comment]
Instructions updated: https://github.com/vmware/vca-cli#mac-os-x
