### ISSUE TITLE
Error when deleting vApp

### ISSUE THREAD

**Issue by hardevsanghera** [vmware/vca-cli#13]
deleting vApp 't_TESTHS' from VDC 'M86......-4840'
Traceback (most recent call last):
  File "/usr/local/bin/vca", line 9, in <module>
    load_entry_point('vca-cli==12rc3', 'console_scripts', 'vca')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/vca_cli.py", line 495, in vapp
    task = vca.delete_vapp(vdc, vapp)
  File "/usr/local/lib/python2.7/dist-packages/pyvcloud/vcloudair.py", line 405, in delete_vapp
    if vapp: return vapp.delete()
  File "/usr/local/lib/python2.7/dist-packages/pyvcloud/vapp.py", line 125, in delete
    return self.execute("remove", "delete")
  File "/usr/local/lib/python2.7/dist-packages/pyvcloud/vapp.py", line 79, in execute
    self.response = Http.delete(link[0].get_href(), headers=self.headers, verify=self.verify, logger=self.logger)
  File "/usr/local/lib/python2.7/dist-packages/pyvcloud/__init__.py", line 65, in delete
    response = requests.delete(url, data, **kwargs)
NameError: global name 'data' is not defined

vca --version
vca-cli version 12rc3 (pyvcloud: 13rc3)

**Comment by pacogomez** [comment]
this has been fixed, please update vca-cli with:
pip install vca-cli --pre --upgrade
