### ISSUE TITLE
Cannot enumerate templates in catalog

### ISSUE THREAD

**Issue by jicowan** [vmware/vca-cli#2]
<h6> After running the *vca catalog* command to get a list of the available catalogs
<h5> PS C:\Users\User> vca catalogs
Available catalogs in datacenter MyDC for 'default' profile:
| Catalog            |   # Templates |   # Media | Owner             | Published   | Shared   |
|--------------------+---------------+-----------+-------------------+-------------+----------|
| Vagrant            |             1 |         0 | user@vmware.com | false       | false    |
| Public Catalog     |            15 |         0 | system            | true        | true     |
| Enterprise Catalog |             8 |         7 | user@vmware.com | false       | true     |
<h6> and running the *vca templates --catalog 'Enterprise Catalog'* command, I get the following error: 
<h5> PS C:\Users\User> vca templates --catalog 'Enterprise Catalog'
Available templates in datacenter 'MyDC' for 'default' profile:
Traceback (most recent call last):
  File "C:\Python27\Scripts\vca-script.py", line 9, in <module>
    load_entry_point('vca-cli==0.5', 'console_scripts', 'vca')()
  File "C:\Python27\lib\site-packages\click\core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 590, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python27\lib\site-packages\click\core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "C:\Python27\lib\site-packages\vca_cli\vca_cli.py", line 783, in templates
    table = vcd.list_templates({'--catalog': catalog})
  File "C:\Python27\lib\site-packages\pyvcloud\vclouddirector.py", line 154, in list_templates
    memory = int(vAppTemplateRecord.get("memoryAllocationMB")) / 1024
TypeError: int() argument must be a string or a number, not 'NoneType'
<h6> When I ask for a list of the templates in the Public Catalog and the Vagrant catalog, it works fine.

**Comment by pacogomez** [comment]
please use the command 'vca catalog' to list catalog and templates, this has changed in the current version. We'll provide more information about templates in the future
