### ISSUE TITLE
option 'verify' is not transmitted to the function 'display_progress' in the vca_cli.py

### ISSUE THREAD

**Issue by kastesh** [vmware/vca-cli#21]
We have got the error when we using --insecure option.
```
 vca --insecure vapp create --vapp .....
progress : [*     ] 1 %Traceback (most recent call last):
File "/bin/vca", line 9, in <module>
load_entry_point('vca-cli==12', 'console_scripts', 'vca')()
File "/usr/lib/python2.7/site-packages/click/core.py", line 664, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/click/core.py", line 644, in main
rv = self.invoke(ctx)
File "/usr/lib/python2.7/site-packages/click/core.py", line 991, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python2.7/site-packages/click/core.py", line 837, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python2.7/site-packages/click/core.py", line 464, in invoke
return callback(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 649, in vapp
vca.vcloud_session.get_vcloud_headers())
File "/usr/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 2444, in display_progress
response = requests.get(task.get_href(), headers=headers)
File "/usr/lib/python2.7/site-packages/requests/api.py", line 65, in get
return request('get', url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/api.py", line 49, in request
response = session.request(method=method, url=url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
```

Feature request: 
It would be nice if the option 'insecure' is set  than warning will not show:
```
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
```

Thank you for the very useful utility!

**Comment by pacogomez** [comment]
this has been fixed/improved, use:

pip install vca-cli --pre --upgrade
