### ISSUE TITLE
Issues after installing on OSX 10.10.4

### ISSUE THREAD

**Issue by cstewart87** [vmware/vca-cli#27]
After a successful installation on OSX 10.10.4, i receive the following error.

```
$ vca --version
Traceback (most recent call last):
  File "/usr/local/bin/vca", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six>=1.9.0
```

**Comment by anshimagupta** [comment]
Instead of upgrading through pip, can you try 
"easy_install --upgrade six"

**Comment by cstewart87** [comment]
:+1: thanks!  that worked
