### ISSUE TITLE
Traceback on vca status

### ISSUE THREAD

**Issue by amwelch** [vmware/vca-cli#34]
After logging in vca status gives a traceback:

Traceback (most recent call last):
  File "/usr/local/bin/vca", line 9, in <module>
    load_entry_point('vca-cli==13', 'console_scripts', 'vca')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/vca_cli_impl.py", line 346, in status
    if prop == 'password' and len(ctx.obj.get(prop, [])) > 0:
TypeError: object of type 'NoneType' has no len()

Running on the latest stable from pip:
vca --version
vca-cli version 13 (pyvcloud: 14rc6)

**Comment by pacogomez** [comment]
the session id has probably expired and the login was done without the --save-password flag. This has been fixed in the latest development version (pip install vca-cli --upgrade --pre), please note that there are also some minor changes in the login and vapp commands

**Comment by amwelch** [comment]
Ah, great! Thanks for the quick response.

**Comment by sameersbn** [comment]
I have the same issue. Doing `pip install vca-cli --upgrade --pre` completely breaks `vca-cli`

```bash
vca login email@example.com
Traceback (most recent call last):
  File "/usr/local/bin/vca", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/vca_cli.py", line 70, in cli
    ctx.obj.load_config(profile, profile_file)
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/cmd_proc.py", line 87, in load_config
    password = cipher_suite.decrypt(password)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/fernet.py", line 85, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken
```

**Comment by pacogomez** [comment]
this is a known issue during the upgrade, as a work around, remove ~/.vcarc, you will need to re-login

**Comment by sameersbn** [comment]
Using `--save-password` at login fixes `vca status`. Thanks!

**Comment by pacogomez** [comment]
in the latest version (14c3) , login saves the password by default

**Comment by sameersbn** [comment]
@pacogomez thanks. the upgrade works after deleting `~/.vcarc`
