### ISSUE TITLE
create vapp randomly succeeds

### ISSUE THREAD

**Issue by sameersbn** [vmware/vca-cli#36]
I am trying to create a VM using `vca` cli using the following command

```bash
vca vapp create --vapp myvapp \
--catalog 'Public Catalog' \
--template 'Ubuntu Server 12.04 LTS (amd64 20150127)' \
--network default-routed-network \
--mode pool \
--vm myvm \
--cpu 2 \
--ram 8
```

The output is:

```bash
creating vApp 'myvapp' in VDC 'VDC1' from template 'Ubuntu Server 12.04 LTS (amd64 20150127)' in catalog 'Public Catalog'
progress : [**************************************************************************************************** ] 100 
<Error message="[ 7a2fab8c-40fb-4ca6-aedf-70ec17fed279 ] Unable to perform this action. Contact your cloud administrator." minorErrorCode="INTERNAL_SERVER_ERROR" majorErrorCode="500"/>
setting computer name for VM 'myvm'
Traceback (most recent call last):
  File "/usr/local/bin/vca", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/vca_cli_compute.py", line 355, in vapp
    utils.print_error("can't set computer name", cmd_proc)
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/vca_cli_utils.py", line 52, in print_error
    json_message = json.loads(cmd_proc.vca.response.content)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Sometimes the above command works, but most of the times it fails.

> Note: the following warning is displayed on the terminal `util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning`

I have installed vca-cli using these instructions of the readme: https://github.com/vmware/vca-cli#ubuntu on a 12.04 host.

**Comment by sameersbn** [comment]
I switched to the Japan location and this issue was gone. Thanks!
