### ISSUE TITLE
Fresh install fails, on OSX

### ISSUE THREAD

**Issue by robinbowes** [vmware/vca-cli#48]
I created a new virtual env, activated it and installed vca-cli with pip.

I get this error:
```
  vca --version
Traceback (most recent call last):
  File "/Users/robin/dwp/vca/venv/bin/vca", line 7, in <module>
    from vca_cli.vca_cli import cli
  File "/Users/robin/dwp/vca/venv/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 542, in <module>
    import vca_cli_blueprint  # NOQA
  File "/Users/robin/dwp/vca/venv/lib/python2.7/site-packages/vca_cli/vca_cli_blueprint.py", line 23, in <module>
    from dsl_parser.exceptions import \
ImportError: No module named dsl_parser.exceptions
```

This is Python 2.7.12, installed from brew on OSX

**Comment by pacogomez** [comment]
a module is missing in the requirements.txt

run:

pip install cloudify-dsl-parser

We'll add this module on the requirements.txt

**Comment by benklop** [comment]
FYI, I've hit this issue too. +1 on a fix to requirements.txt

**Comment by kbrems** [comment]
I also ran into the install issue with dsl_parser on macOS 10.12.4. Then I tried the suggested fix:

sudo -H pip install cloudify-dsl-parser

but then I get the error:
    ...
    copying networkx/utils/tests/test_decorators.py -> build/lib/networkx/utils/tests
    copying networkx/utils/tests/test_misc.py -> build/lib/networkx/utils/tests
    copying networkx/utils/tests/test_random_sequence.py -> build/lib/networkx/utils/tests
    copying networkx/utils/tests/test_rcm.py -> build/lib/networkx/utils/tests
    running install_lib
    running install_data
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-rsh5v3/networkx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-GneHDM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-rsh5v3/networkx/
