### ISSUE TITLE
Can't login to vCloud Director

### ISSUE THREAD

**Issue by zoquero** [vmware/vca-cli#49]
Hola desde Barcelona, Paco!

  I have followed up the examples to try to login into a vCloud Director Standalone instance but **I can't login**:

  I have installed **pycloud** and **vca-cli** via pip on a virtual environment on Ubuntu 15.04 and I have upgraded all the modules. I'm using a user "_MYUSERNAME_" to manage an organitzation called "_MYORG_" that has a vDC called "_MYVDC_" on the vCloud Director 5.5 _https://myvcloud.mydomain_ . I can successfully manage it using the regular Web Interface but I can't login via vca-cli using any of these commands:

```
$ vca --insecure login MYUSERNAME@MYORG --password MYPASSWORD --host https://myvcloud.mydomain --org MYORG --version 5.5
$ vca --insecure login MYUSERNAME       --password MYPASSWORD --host https://myvcloud.mydomain --org MYORG --version 5.5

$ vca --insecure login MYUSERNAME@MYORG --password MYPASSWORD --host https://myvcloud.mydomain --org MYORG --vdc MYVDC --version 5.5
$ vca --insecure login MYUSERNAME       --password MYPASSWORD --host https://myvcloud.mydomain --org MYORG --vdc MYVDC --version 5.5
```

  But I always get a:
`Can't login: Access is forbidden`

  What's wrong? Thanks and best regards.
  /Ángel

**Comment by zoquero** [comment]
Ah, maybe it's useful, this is my pip list:

```
(venv) $ pip list 
Babel (2.3.4)
cffi (1.7.0)
click (6.6)
cloudify-dsl-parser (3.4)
colorama (0.3.7)
cryptography (1.4)
debtcollector (1.6.0)
decorator (4.0.10)
enum34 (1.1.6)
funcsigs (1.0.2)
idna (2.1)
ipaddress (1.0.16)
iptools (0.6.1)
iso8601 (0.1.11)
lxml (3.6.1)
monotonic (1.1)
netaddr (0.7.18)
netifaces (0.10.4)
networkx (1.11)
oslo.i18n (3.8.0)
oslo.utils (3.16.0)
pbr (1.10.0)
pip (8.1.2)
prettytable (0.7.2)
progressbar (2.3)
pyasn1 (0.1.9)
pycparser (2.14)
pyparsing (2.1.5)
python-dateutil (2.5.3)
pytz (2016.6.1)
pyvcloud (16)
PyYAML (3.10)
requests (2.10.0)
retrying (1.3.3)
setuptools (25.1.1)
six (1.10.0)
tabulate (0.7.5)
vca-cli (17)
wheel (0.29.0)
wrapt (1.10.8)
xmltodict (0.10.2)
```

  Best regards,
/Ángel

**Comment by pfink** [comment]
I have exactly the same issue!

**Comment by zoquero** [comment]
HI, Patrick:
Looks like it's no longer maintained. After that I wrote my own set of scripts for vCloud Director 5.5, it allows you at least to show Inventory, graph it and also show firewall rules: https://github.com/zoquero/vcloudtools . With upcomming vCD 8 it all will change...
Best regards,
/Angel

**Comment by pfink** [comment]
Thanks! Meanwhile, I directly used pyvcloud to accomplish my tasks...

**Comment by flamby** [comment]
Hi,
Even w/ latest vca-cli version 18 (pyvcloud: 16), I can't login either :

```
Traceback (most recent call last):
  File "/Users/user/Sites/virtualenvs/vca-cli/bin/vca", line 11, in <module>
    load_entry_point('vca-cli==18', 'console_scripts', 'vca')()
  File "/Users/user/Sites/virtualenvs/vca-cli/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/Sites/virtualenvs/vca-cli/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/user/Sites/virtualenvs/vca-cli/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/user/Sites/virtualenvs/vca-cli/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/Sites/virtualenvs/vca-cli/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/Sites/virtualenvs/vca-cli/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/Sites/virtualenvs/vca-cli/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 70, in cli
    ctx.obj.load_config(profile, profile_file)
  File "/Users/user/Sites/virtualenvs/vca-cli/lib/python2.7/site-packages/vca_cli/cmd_proc.py", line 87, in load_config
    password = cipher_suite.decrypt(password)
  File "/Users/user/Sites/virtualenvs/vca-cli/lib/python2.7/site-packages/cryptography/fernet.py", line 85, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken
```

any thought?

**Comment by pacogomez** [comment]
try to remove the 'password = ' entries in the ~/.vcarc file and run again the login command

**Comment by flamby** [comment]
Hi @pacogomez 

thanks, it worked.

perhaps error message should be more explicit when a previous profile of the .vcarc is used instead of the command arguments, or better .vcarc should be ignored once arguments are provided.

**Comment by pacogomez** [comment]
does vCloud have self-signed certificates? if yes, then use `vca -i ...`

**Comment by merlin145160** [comment]
Hi,
It seems to be the same error I had last November. Even if you install vcd-cli from pip, I figure out that pyvcloud main librairy was outdated. So I've git it directly in my system.
I hope this error release will be fixed next release.
$cd
$git clone https://github.com/vmware/pyvcloud.git
$rm -rf ~/.local/lib/python2.7/site-packages/pyvcloud
$mv pyvcloud/ /home/nicolas/.local/lib/python2.7/site-packages/
I hope this will solve your python environment issue
Good luck with python packaging
